{% set name = "gradio-client" %}
{% set version = "1.13.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gradio_client-{{ version }}.tar.gz
  sha256: 869b3e67e0f7a0f40df8c48c94de99183265cf4b7b1d9bd4623e336d219ffbe7

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - hatchling
    - hatch-requirements-txt
    - hatch-fancy-pypi-readme >=22.5.0
    - pip
  run:
    - python
    - fsspec
    - httpx >=0.24.1
    - huggingface_hub >=0.19.3,<2.0
    - packaging
    - typing_extensions ~=4.0
    - websockets >=10.0,<16.0

test:
  imports:
    - gradio_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/gradio-client/
  doc_url: https://www.gradio.app/
  dev_url: https://github.com/gradio-app/gradio
  summary: Python library for easily interacting with trained machine learning models
  description: Python library for easily interacting with trained machine learning models
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache

extra:
  recipe-maintainers:
    - abidlabs
    - Sclare87
