{% set name = "gradio-client" %}
{% set version = "2.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 4cde99bad62149595c30c90876ca2e405e3a13687ecf895474f3412cb476673d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - hatchling
    - hatch-requirements-txt
    - hatch-fancy-pypi-readme >=22.5.0
  run:
    - python
    - fsspec
    - httpx >=0.24.1
    - huggingface_hub >=0.19.3,<2.0
    - packaging
    - typing_extensions >=4.0,<5

test:
  imports:
    - gradio_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/gradio-client
  doc_url: https://www.gradio.app
  dev_url: https://github.com/gradio-app/gradio
  summary: Python library for easily interacting with trained machine learning models
  description: Python library for easily interacting with trained machine learning models
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache

extra:
  recipe-maintainers:
    - abidlabs
    - Sclare87
